CREATE DATABASE DOOMBOX

CREATE TABLE USUARIO
(
LOGIN_USUARIO VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
SENHA VARCHAR(30) NOT NULL,
PRIMARY KEY(LOGIN_USUARIO)
)

INSERT INTO USUARIO VALUES ('MASTER', 'MASTER', 'MASTER')

SELECT * FROM USUARIO

CREATE TABLE ARQ_DIR
(
ID SMALLINT IDENTITY(1,1) NOT NULL,
NOME VARCHAR(40) NOT NULL,
PAI SMALLINT,
DIRETORIO SMALLINT NOT NULL,
DATA TIMESTAMP,
BYTES DECIMAL, 
LOGIN_USUARIO VARCHAR(30),
DESCRICAO VARCHAR(100),

PRIMARY KEY (ID),
FOREIGN KEY(LOGIN_USUARIO) REFERENCES USUARIO(LOGIN_USUARIO),
FOREIGN KEY(PAI) REFERENCES ARQ_DIR(ID)
)
